### ISSUE TITLE
Bigger text string

### ISSUE THREAD

**Issue by JyskMaker** [HobbyComponents/HCWS2812#1]
How to make a bigger text string, its only 19 char??
Thanks for the good work :-)

**Comment by HobbyComponents** [comment]
It should be able to handle strings longer than 19 characters. Have you changed the value for  NUMBEROFLEDS in the header file (HCWS2812.h) to match the number of LEDs you have?

If that doesn't fix your problem try modifying the  HCWS2812_Message_Display_Example sketch that comes with the library to rule out a bug in you sketch. Remember to increase the loop count in the for loop.

**Comment by JyskMaker** [comment]
Yes i have. :-) maby its the loop counter. Its one og your sketch i uses to
test it with.
Den 25/06/2016 10.50 skrev "Hobby Components" notifications@github.com:

It should be able to handle strings longer than 19 characters. Have you
changed the value for NUMBEROFLEDS in the header file (HCWS2812.h) to match
the number of LEDs you have?

If that doesn't fix your problem try modifying the
HCWS2812_Message_Display_Example sketch that comes with the library to rule
out a bug in you sketch. Remember to increase the loop count in the for
loop.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
https://github.com/HobbyComponents/HCWS2812/issues/1#issuecomment-228524806,
or mute the thread
https://github.com/notifications/unsubscribe/ACcN3guoOaElzZnfY60Z2o0wAfJ8g_6Dks5qPOvLgaJpZM4I9yLe
.

**Comment by HobbyComponents** [comment]
Try this:

```
#include "HCWS2812.h"

HCWS2812 HCWS2812;

void setup() 
{
    HCWS2812.SetFontFG(50, 50, 50);
    HCWS2812.SetBG(0, 0, 0);
}

void loop() 
{
  for(int index = 0; index < 288; index++)
  {
    HCWS2812.ClearBuffer();

    HCWS2812.print("ABCDEFGHIJKLMNOPQRSTUVWXYZ123456789", index);

    HCWS2812.Refresh();

    delay(80);  
  }    
}

Edit: Yes, you'll need to increase the value in the for loop by 8 for every character you add.
```
